function bind() {
  $('#nav').onclick = e => { const b = e.target.closest('button'); if (b) navigate(b.dataset.page); };
  $$('[data-page-target]').forEach(b => b.onclick = () => navigate(b.dataset.pageTarget));
  setInterval(() => $('#dayClock').textContent = new Date().toLocaleTimeString('pt-BR'), 1000);
  $('.avatar').onclick = async () => { await window.showApp.logout(); location.href = 'login.html'; };
  $('#openScreen').onclick = $('#dayScreen').onclick = () => window.showApp.openScreen().catch(e => toast(e.message));
  $('#toggleEvent').onclick = async () => { if (!canOperate()) return; state.event.status = state.event.status === 'live' ? 'closed' : 'live'; audit(state.event.status === 'live' ? 'Evento iniciado' : 'Evento encerrado'); await persist('Status atualizado.'); };

  $('#newSale').onclick = () => { if (!canOperate()) return; $('#saleDialog').showModal(); renderSellers(); $('#saleTotal').textContent = money(saleValue(Number($('#cardQty').value))); };
  $('#cardQty').oninput = () => $('#saleTotal').textContent = money(saleValue(Number($('#cardQty').value)));
  $('#saleForm').onsubmit = async e => {
    e.preventDefault(); if (!canOperate()) return;
    const qty = Number($('#cardQty').value); if (!Number.isInteger(qty) || qty < 1 || qty > 100) return toast('Quantidade de cartelas inválida.');
    const buyer = $('#buyerName').value.trim(); if (!buyer) return toast('Informe o nome do comprador.');
    const seq = nextSequence('sale'), code = `${state.settings.prefix}-${String(seq).padStart(4, '0')}`, id = crypto.randomUUID();
    if (state.sales.some(s => s.code === code)) return toast('Código de venda duplicado. Atualize o banco antes de continuar.');
    const seller = state.sellers.find(s => String(s.id) === String($('#saleSeller').value)) || state.sellers[0]; if (!seller) return toast('Cadastre um vendedor antes de registrar a venda.');
    const sale = { id, code, buyer, cpf: $('#buyerCpf').value.trim(), phone: $('#buyerPhone').value.trim(), qty, value: saleValue(qty), at: now(), seller: seller.name, sellerId: seller.id, method: $('#paymentMethod').value, status: 'valid', priceSnapshot: { unit: state.settings.salePrice, triple: state.settings.triplePrice } };
    state.sales.unshift(sale); state.customers.push({ id: crypto.randomUUID(), name: sale.buyer, cpf: sale.cpf, phone: sale.phone, createdAt: sale.at });
    let template = null; for (let i = 0; i < qty; i++) { const c = createCard(`${code}-${String(i + 1).padStart(2, '0')}`, id, 'DIGITAL'); if (state.settings.cardMode === 'fixed') { template ||= c.numbers; c.numbers = [...template]; } state.cards.push(c); }
    audit(`Venda ${code} registrada em ${methodName(sale.method)}`); $('#saleDialog').close(); e.target.reset(); $('#cardQty').value = 1; await persist('Venda registrada.');
  };
  $('#saleSearch').oninput = renderSales; $('#saleStatus').onchange = $('#saleMethod').onchange = renderSales;

  $('#addRound').onclick = async () => { if (!canOperate()) return; const id = (state.rounds.at(-1)?.id || 0) + 1; state.rounds.push({ id, name: `${id}ª Rodada`, prizes: [], status: 'waiting', drawn: [], drawLog: [] }); state.event.rounds = state.rounds.length; audit(`Rodada ${id} criada`); await persist('Nova rodada criada.'); };
  $('#roundRows').onchange = async e => { if (!canOperate()) return; let parts; if (e.target.dataset.roundName) { state.rounds.find(r => r.id === Number(e.target.dataset.roundName)).name = e.target.value; } else if (e.target.dataset.prizeName) { parts = e.target.dataset.prizeName.split(':'); state.rounds.find(r => r.id === Number(parts[0])).prizes.find(p => p.id === Number(parts[1])).name = e.target.value; } else if (e.target.dataset.prizeValue) { parts = e.target.dataset.prizeValue.split(':'); state.rounds.find(r => r.id === Number(parts[0])).prizes.find(p => p.id === Number(parts[1])).value = Math.max(0, Number(e.target.value)); } else if (e.target.dataset.prizePattern) { parts = e.target.dataset.prizePattern.split(':'); state.rounds.find(r => r.id === Number(parts[0])).prizes.find(p => p.id === Number(parts[1])).pattern = e.target.value; } else return; audit('Rodada ou prêmio alterado'); await persist('Alteração salva.'); };
  $('#suggestPrizes').onclick = async () => { if (!canOperate()) return; const pool = totals().sales * Number(state.settings.prizePercent || 0) / 100, first = Math.round(pool * Number(state.settings.firstPrizeShare || 0) / 100 / 10) * 10, second = Math.round(pool * Number(state.settings.secondPrizeShare || 0) / 100 / 10) * 10; const r = state.rounds[0]; if (!r || state.winners.some(w => String(w.roundId) === String(r.id) && w.status !== 'canceled')) return toast('A primeira rodada já possui vencedor e não pode ter a premiação recalculada.'); r.prizes = [{ id: Date.now(), name: '1º Prêmio', value: first, pattern: 'FULL' }, { id: Date.now() + 1, name: '2º Prêmio', value: second, pattern: 'FULL' }]; audit('Premiação sugerida'); await persist(`Sugestão: ${money(first)} e ${money(second)}.`); };

  $('#drawRound').onchange = renderDraw;
  $('#drawMode').onchange = async () => { state.settings.drawMode = $('#drawMode').value; await persist(); };
  $('#drawNumber').onclick = () => { const r = state.rounds.find(x => x.id === Number($('#drawRound').value)); if (!r || r.drawn.length >= 75) return toast('Todos os 75 números já foram sorteados.'); const remaining = Array.from({ length: 75 }, (_, i) => i + 1).filter(n => !r.drawn.includes(n)); const n = remaining[Math.floor(Math.random() * remaining.length)]; addDraw(n, $('#drawMode').value === 'click' ? 'click' : 'automatic'); };
  $('#currentBall').onclick = () => { if ($('#drawMode').value === 'click') $('#drawNumber').click(); };
  $('#confirmManual').onclick = () => addDraw($('#manualNumber').value, 'manual');
  $('#undoNumber').onclick = async () => { if (!canOperate()) return; const r = state.rounds.find(x => x.id === Number($('#drawRound').value)); if (!r) return; if (state.winners.some(w => String(w.roundId) === String(r.id) && Number(w.drawIndex) === r.drawn.length && w.status !== 'canceled')) return toast('Não é possível desfazer a bola que confirmou um vencedor.'); const n = r.drawn.pop(); r.drawLog.pop(); if (n) { audit(`Sorteio ${n} desfeito`); await persist('Último número removido.'); } };

  $('#newSeller').onclick = () => { if (!canManage()) return; simpleDialog('Novo vendedor', [{ id: 'name', label: 'Nome', required: true }, { id: 'phone', label: 'Telefone' }, { id: 'email', label: 'E-mail', type: 'email' }, { id: 'commission', label: 'Comissão (%)', type: 'number', value: 0 }], async () => { state.sellers.push({ id: Date.now(), name: $('#sf_name').value.trim(), phone: $('#sf_phone').value.trim(), email: $('#sf_email').value.trim(), commission: Math.max(0, Number($('#sf_commission').value)), active: true }); audit('Vendedor cadastrado'); await persist('Vendedor cadastrado.'); }); };
  $('#newUser').onclick = () => { if (!canManage()) return; simpleDialog('Novo usuário', [{ id: 'name', label: 'Nome', required: true }, { id: 'phone', label: 'Telefone' }, { id: 'email', label: 'E-mail', type: 'email' }, { id: 'login', label: 'Login', required: true }, { id: 'password', label: 'Senha inicial', type: 'password', required: true, minlength: 8 }, { id: 'role', label: 'Perfil', type: 'select', options: [{ value: 'ADMIN', label: 'Administrador' }, { value: 'OPERATOR', label: 'Operador' }, { value: 'VIEWER', label: 'Consulta' }] }], async () => { const login = $('#sf_login').value.trim(); if (state.users.some(u => u.login.toLowerCase() === login.toLowerCase())) return toast('Este login já existe.'); const id = Date.now(), password = $('#sf_password').value; state.users.push({ id, name: $('#sf_name').value.trim(), phone: $('#sf_phone').value.trim(), email: $('#sf_email').value.trim(), login, role: $('#sf_role').value, active: true }); audit('Usuário cadastrado'); if (await persist()) { try { await window.showApp.setUserPassword(id, password); state = await window.showApp.load(); renderAll(); toast('Usuário cadastrado.'); } catch (e) { toast(e.message); } } }); };
  $('#simpleForm').onsubmit = async e => { e.preventDefault(); const fn = simpleSave; simpleSave = null; $('#simpleDialog').close(); if (fn) await fn(); };

  document.addEventListener('click', async e => {
    const b = e.target.closest('[data-add-prize],[data-delete-prize],[data-delete-round],[data-edit-seller],[data-delete-seller],[data-edit-user],[data-delete-user],[data-print-card],[data-delete-card],[data-db-delete],[data-db-edit],[data-cancel-sale],[data-pay-winner]'); if (!b) return;
    if (b.dataset.addPrize && canOperate()) { const r = state.rounds.find(x => x.id === Number(b.dataset.addPrize)); r.prizes.push({ id: Date.now(), name: `${r.prizes.length + 1}º Prêmio`, value: 0, pattern: 'FULL' }); audit(`Prêmio adicionado à rodada ${r.id}`); return persist('Prêmio adicionado.'); }
    if (b.dataset.deletePrize && isMaster()) { const [rid, pid] = b.dataset.deletePrize.split(':').map(Number); if (winnerForPrize(rid, pid)) return toast('Prêmio com vencedor não pode ser excluído.'); const round = state.rounds.find(x => x.id === rid); round.prizes = round.prizes.filter(x => x.id !== pid); audit(`Prêmio excluído da rodada ${rid}`); return persist('Prêmio excluído.'); }
    if (b.dataset.deleteRound && isMaster()) { const rid = Number(b.dataset.deleteRound); if (state.winners.some(w => String(w.roundId) === String(rid) && w.status !== 'canceled')) return toast('Rodada com vencedor não pode ser excluída.'); state.rounds = state.rounds.filter(x => x.id !== rid).map((r, i) => ({ ...r, id: i + 1, name: r.name.replace(/^\d+/, String(i + 1)) })); state.event.rounds = state.rounds.length; audit(`Rodada ${rid} excluída`); return persist('Rodada excluída.'); }
    if (b.dataset.editSeller && canManage()) { const s = state.sellers.find(x => String(x.id) === String(b.dataset.editSeller)); return simpleDialog('Alterar vendedor', [{ id: 'name', label: 'Nome', required: true, value: s.name }, { id: 'phone', label: 'Telefone', value: s.phone }, { id: 'email', label: 'E-mail', type: 'email', value: s.email }, { id: 'commission', label: 'Comissão (%)', type: 'number', value: s.commission }], async () => { Object.assign(s, { name: $('#sf_name').value.trim(), phone: $('#sf_phone').value.trim(), email: $('#sf_email').value.trim(), commission: Math.max(0, Number($('#sf_commission').value)) }); audit('Vendedor alterado'); await persist('Vendedor alterado.'); }); }
    if (b.dataset.deleteSeller && isMaster()) { const id = Number(b.dataset.deleteSeller); if (validSales().some(s => String(s.sellerId) === String(id))) return toast('Vendedor com vendas registradas não pode ser excluído. Desative-o pelo banco se necessário.'); state.sellers = state.sellers.filter(x => x.id !== id); audit('Vendedor excluído'); return persist('Vendedor excluído.'); }
    if (b.dataset.editUser && canManage()) { const u = state.users.find(x => String(x.id) === String(b.dataset.editUser)); if (u.role === 'MASTER') return toast('O Administrador Master é protegido.'); return simpleDialog('Alterar usuário', [{ id: 'name', label: 'Nome', value: u.name, required: true }, { id: 'phone', label: 'Telefone', value: u.phone }, { id: 'email', label: 'E-mail', type: 'email', value: u.email }, { id: 'login', label: 'Login', value: u.login, required: true }, { id: 'password', label: 'Nova senha (opcional)', type: 'password', minlength: 8 }, { id: 'role', label: 'Perfil', type: 'select', value: u.role, options: [{ value: 'ADMIN', label: 'Administrador' }, { value: 'OPERATOR', label: 'Operador' }, { value: 'VIEWER', label: 'Consulta' }] }], async () => { const login = $('#sf_login').value.trim(); if (state.users.some(x => x.id !== u.id && x.login.toLowerCase() === login.toLowerCase())) return toast('Este login já existe.'); Object.assign(u, { name: $('#sf_name').value.trim(), phone: $('#sf_phone').value.trim(), email: $('#sf_email').value.trim(), login, role: $('#sf_role').value }); const password = $('#sf_password').value; audit('Usuário alterado'); if (await persist('Usuário alterado.') && password) { try { await window.showApp.setUserPassword(u.id, password); toast('Senha atualizada.'); } catch (err) { toast(err.message); } } }); }
    if (b.dataset.deleteUser && isMaster()) { const u = state.users.find(x => String(x.id) === String(b.dataset.deleteUser)); if (!u || u.role === 'MASTER') return toast('O Administrador Master não pode ser excluído.'); state.users = state.users.filter(x => x.id !== u.id); audit(`Usuário ${u.login} excluído`); return persist('Usuário excluído.'); }
    if (b.dataset.printCard) return printChosenCards([b.dataset.printCard]);
    if (b.dataset.deleteCard && isMaster()) { const id = b.dataset.deleteCard; if (state.winners.some(w => (w.cardIds || []).includes(id) && w.status !== 'canceled')) return toast('Cartela premiada não pode ser excluída.'); state.cards = state.cards.filter(x => x.id !== id); audit(`Cartela ${id} excluída`); return persist('Cartela excluída.'); }
    if (b.dataset.cancelSale && canManage()) { const sale = state.sales.find(s => s.id === b.dataset.cancelSale); if (!sale || sale.status !== 'valid') return; const cards = state.cards.filter(c => c.saleId === sale.id); if (state.winners.some(w => (w.cardIds || []).some(id => cards.some(c => c.id === id)) && w.status !== 'canceled')) return toast('Venda com cartela premiada não pode ser cancelada.'); sale.status = 'canceled'; sale.canceledAt = now(); sale.canceledBy = currentUser().name; cards.forEach(c => c.status = 'canceled'); audit(`Venda ${sale.code} cancelada`); return persist('Venda cancelada e cartelas invalidadas.'); }
    if (b.dataset.payWinner && canManage()) { const w = state.winners.find(x => x.id === b.dataset.payWinner); if (!w || w.status !== 'pending') return; w.status = 'paid'; w.paidAt = now(); w.paidBy = currentUser().name; audit(`Prêmio ${w.prizeName} pago para ${w.cardCodes.join(', ')}`); return persist('Pagamento do prêmio registrado.'); }
    if (b.dataset.dbDelete && isMaster()) { const [table, index] = b.dataset.dbDelete.split(':'); if (table === 'audit') return toast('A auditoria é protegida contra exclusão.'); if (table === 'users' && state[table][index]?.role === 'MASTER') return toast('Master protegido.'); state[table].splice(Number(index), 1); audit(`Registro excluído do banco: ${table}`); return persist('Registro excluído.'); }
    if (b.dataset.dbEdit && isMaster()) { const [table, index] = b.dataset.dbEdit.split(':'); if (table === 'audit' || (table === 'users' && state[table][index]?.role === 'MASTER')) return toast('Registro protegido.'); const row = state[table][index]; return simpleDialog('Editar registro JSON', [{ id: 'json', label: 'JSON completo', value: JSON.stringify(row) }], async () => { try { state[table][index] = JSON.parse($('#sf_json').value); audit(`Registro alterado no banco: ${table}`); await persist('Registro alterado.'); } catch { toast('JSON inválido.'); } }); }
  });

  $('#newWithdrawal').onclick = () => { if (canOperate()) $('#withdrawDialog').showModal(); };
  $('#withdrawForm').onsubmit = async e => { e.preventDefault(); if (!canOperate()) return; const value = Number($('#withdrawValue').value); if (!(value > 0)) return toast('Informe um valor de retirada válido.'); state.withdrawals.unshift({ id: crypto.randomUUID(), description: $('#withdrawDesc').value.trim(), value, at: now(), user: currentUser().name }); audit('Retirada registrada'); $('#withdrawDialog').close(); e.target.reset(); await persist('Retirada registrada.'); };
  $('#closeCash').onclick = () => { if (!canManage()) return; simpleDialog('Fechamento de caixa', [{ id: 'counted', label: 'Valor contado (R$)', type: 'number', required: true, value: totals().cashBalance }], async () => { const expected = totals().cashBalance, counted = Number($('#sf_counted').value); state.cashClosings.unshift({ id: crypto.randomUUID(), at: now(), expected, counted, difference: counted - expected, user: currentUser().name }); audit(`Caixa fechado; diferença ${money(counted - expected)}`); await persist(`Diferença: ${money(counted - expected)}.`); }); };

  $('#savePix').onclick = async () => { if (!canManage()) return; state.settings.pix = { enabled: $('#pixEnabled').checked, keyType: $('#pixType').value, key: $('#pixKey').value.trim(), name: $('#pixName').value.trim(), city: $('#pixCity').value.trim(), description: $('#pixDescription').value.trim(), banner: $('#pixBanner').value.trim() }; audit('PIX atualizado'); await persist('Configuração PIX salva.'); };
  $('#testPix').onclick = async () => { try { const p = { keyType: $('#pixType').value, key: $('#pixKey').value.trim(), name: $('#pixName').value.trim(), city: $('#pixCity').value.trim(), description: $('#pixDescription').value.trim() }, r = await window.showApp.pixQr(p, Number($('#pixTestValue').value), 'TESTE'); $('#pixQr').src = r.dataUrl; $('#pixQr').style.display = 'block'; $('#pixQrEmpty').style.display = 'none'; $('#pixPayload').textContent = r.payload; toast('QR PIX gerado.'); } catch (e) { toast(e.message); } };

  $('#generateCards').onclick = async () => { if (!canOperate()) return; const qty = Math.min(1000, Math.max(1, Number($('#genQty').value))), type = $('#genType').value, mode = $('#genMode').value, batch = Date.now().toString(36).toUpperCase(); let template = null; for (let i = 0; i < qty; i++) { const seq = nextSequence('card'), c = createCard(`${state.settings.prefix}-${String(seq).padStart(4, '0')}`, null, type); if (mode === 'fixed') { template ||= c.numbers; c.numbers = [...template]; } c.batch = batch; state.cards.push(c); } audit(`${qty} cartelas ${type} geradas`); await persist(`${qty} cartelas geradas.`); };
  $('#cardSearch').oninput = renderCards; $('#cardTypeFilter').onchange = renderCards; $('#selectAllCards').onchange = e => $$('.card-select').forEach(c => c.checked = e.target.checked); $('#printCards').onclick = () => printChosenCards($$('.card-select:checked').map(c => c.value));

  $('#buildReports').onclick = buildReports; $('#printReports').onclick = () => { buildReports(); document.body.classList.add('printing-reports'); window.print(); setTimeout(() => document.body.classList.remove('printing-reports'), 500); };
  $('#dbTable').onchange = renderDatabase; $('#dbSearch').oninput = renderDatabase; $('#refreshDatabase').onclick = renderDatabase;

  $('#saveSettings').onclick = async () => { if (!canManage()) return; const count = Math.min(9999, Math.max(1, Number($('#cfgRounds').value))), prefix = $('#cfgPrefix').value.trim().toUpperCase(); if (!/^[A-Z0-9]{1,3}$/.test(prefix)) return toast('O prefixo deve ter 1 a 3 letras ou números.'); Object.assign(state.event, { name: $('#cfgName').value.trim(), date: $('#cfgDate').value, initialCash: Math.max(0, Number($('#cfgCash').value)), rounds: count }); Object.assign(state.settings, { prefix, salePrice: Math.max(0, Number($('#cfgUnit').value)), triplePrice: Math.max(0, Number($('#cfgTriple').value)), prizePercent: Math.min(100, Math.max(0, Number($('#cfgPrizePercent').value))), firstPrizeShare: Math.min(100, Math.max(0, Number($('#cfgFirstShare').value))), secondPrizeShare: Math.min(100, Math.max(0, Number($('#cfgSecondShare').value))), cardMode: $('#cfgMode').value }); while (state.rounds.length < count) { const id = state.rounds.length + 1; state.rounds.push({ id, name: `${id}ª Rodada`, prizes: [], status: 'waiting', drawn: [], drawLog: [] }); } if (count < state.rounds.length && state.rounds.slice(count).some(r => r.drawn.length || state.winners.some(w => String(w.roundId) === String(r.id) && w.status !== 'canceled'))) return toast('Não é possível remover rodadas que já possuem sorteios ou vencedores.'); state.rounds = state.rounds.slice(0, count); audit('Configurações atualizadas'); await persist('Configurações salvas.'); };

  $('#exportBackup').onclick = async () => { try { const r = await window.showApp.exportBackup(); if (r.ok) { state = await window.showApp.load(); renderAll(); toast('Backup exportado.'); } } catch (e) { toast(e.message); } };
  $('#importBackup').onclick = async () => { try { const r = await window.showApp.importBackup(); if (r.ok) { state = r.data; renderAll(); toast('Backup importado.'); } } catch (e) { toast(e.message); } };
}

(async () => {
  try {
    const auth = await window.showApp.authStatus(); if (!auth.authenticated) return location.href = 'login.html';
    state = await window.showApp.load(); bind(); renderAll();
  } catch (e) { toast(e?.message || 'Falha ao iniciar o aplicativo.'); }
})();
