let state;
const $ = s => document.querySelector(s), $$ = s => [...document.querySelectorAll(s)];
const money = v => Number(v || 0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const now = () => new Date().toISOString();
const formatDate = d => new Date(`${d}T12:00:00`).toLocaleDateString('pt-BR',{day:'2-digit',month:'long',year:'numeric'});
const toast = msg => { const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200); };
const audit = action => state.audit.unshift({at:now(),action,user:'Administrador'});
async function persist(message){ await window.showApp.save(state); if(message) toast(message); renderAll(); }

function saleValue(qty){ const triples=Math.floor(qty/3), units=qty%3; return triples*Number(state.settings.triplePrice)+units*Number(state.settings.salePrice); }
function totals(){ const valid=state.sales.filter(s=>s.status==='valid');const sales=valid.reduce((a,s)=>a+s.value,0);const prizes=state.rounds.reduce((a,r)=>a+Number(r.value||0),0);const withdrawals=state.withdrawals.reduce((a,w)=>a+w.value,0);return{sales,prizes,withdrawals,cards:valid.reduce((a,s)=>a+s.qty,0),balance:Number(state.event.initialCash||0)+sales-prizes-withdrawals}; }
function navigate(id){ $$('.page').forEach(p=>p.classList.toggle('active',p.id===id)); $$('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===id)); const b=$(`#nav button[data-page="${id}"] span`);$('#pageTitle').textContent=b?b.textContent:'Show de Prêmios'; }

function renderAll(){
  const t=totals(); $('#eventName').textContent=state.event.name;$('#eventDate').textContent=formatDate(state.event.date);$('#eventStatus').textContent=state.event.status==='live'?'EVENTO EM ANDAMENTO':'EVENTO EM PLANEJAMENTO';
  $('#mSales').textContent=money(t.sales);$('#mSalesCount').textContent=`${state.sales.length} vendas registradas`;$('#mCards').textContent=t.cards;$('#mValid').textContent=`${t.cards} válidas`;$('#mPrizes').textContent=money(t.prizes);$('#mBalance').textContent=money(t.balance);
  renderChart();renderActivity();renderNextRound();renderSales();renderRounds();renderDraw();renderCash();renderReports();renderSettings();
}
function renderChart(){ const amounts=[0,0,0,0,0,0,0];state.sales.filter(s=>s.status==='valid').forEach(s=>amounts[new Date(s.at).getDay()]+=s.value);const max=Math.max(...amounts,1),days=['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'];$('#salesChart').innerHTML=amounts.map((v,i)=>`<div class="bar-item"><b>${v?money(v):''}</b><div class="bar" style="height:${Math.max(3,v/max*145)}px"></div><small>${days[i]}</small></div>`).join(''); }
function renderActivity(){ const entries=[...state.sales.map(s=>({at:s.at,op:`Venda ${s.code}`,user:s.seller,value:s.value,status:s.status})),...state.withdrawals.map(w=>({at:w.at,op:w.description,user:w.user,value:-w.value,status:'completed'}))].sort((a,b)=>b.at.localeCompare(a.at)).slice(0,6);$('#activityRows').innerHTML=entries.length?entries.map(e=>`<tr><td>${new Date(e.at).toLocaleString('pt-BR')}</td><td>${e.op}</td><td>${e.user}</td><td>${money(e.value)}</td><td><span class="pill ${e.status}">${e.status==='valid'?'Confirmada':e.status==='canceled'?'Cancelada':'Concluída'}</span></td></tr>`).join(''):'<tr><td colspan="5">Nenhuma movimentação registrada.</td></tr>'; }
function renderNextRound(){ const r=state.rounds.find(x=>x.status!=='completed')||state.rounds.at(-1);$('#nextRound').innerHTML=`<div class="round-badge">${r.name}<strong>${r.prize||'Prêmio a definir'}</strong></div><div><small>Premiação</small><h2>${money(r.value)}</h2></div><div class="progress"><span style="width:${Math.min(100,r.drawn.length/75*100)}%"></span></div><small>${r.drawn.length} de 75 números sorteados</small>`; }
function renderSales(){ const q=($('#saleSearch')?.value||'').toLowerCase(),status=$('#saleStatus')?.value||'all';const rows=state.sales.filter(s=>(status==='all'||s.status===status)&&[s.buyer,s.cpf,s.phone,s.code].join(' ').toLowerCase().includes(q));$('#salesRows').innerHTML=rows.length?rows.map(s=>`<tr><td><b>${s.code}</b></td><td>${s.buyer}</td><td>${s.phone||'—'}</td><td>${s.qty}</td><td>${money(s.value)}</td><td>${new Date(s.at).toLocaleString('pt-BR')}</td><td><span class="pill ${s.status}">${s.status==='valid'?'Válida':'Cancelada'}</span></td></tr>`).join(''):'<tr><td colspan="7">Nenhuma venda encontrada.</td></tr>'; }
function renderRounds(){ $('#roundRows').innerHTML=state.rounds.map(r=>`<tr><td><b>${r.id}</b></td><td>${r.name}</td><td><input class="editable" data-round="${r.id}" data-field="prize" value="${r.prize||''}" placeholder="Descrição do prêmio"></td><td><input class="editable" type="number" data-round="${r.id}" data-field="value" value="${r.value||0}" min="0" step="10"></td><td><span class="pill ${r.status}">${r.status==='ready'?'Pronta':r.status==='completed'?'Concluída':'Aguardando'}</span></td><td>${r.drawn.length}</td></tr>`).join(''); }
function renderDraw(){ const select=$('#drawRound'),chosen=Number(select.value)||state.rounds.find(r=>r.status!=='completed')?.id||1;select.innerHTML=state.rounds.map(r=>`<option value="${r.id}" ${r.id===chosen?'selected':''}>${r.name} — ${r.prize||'sem prêmio'}</option>`).join('');const r=state.rounds.find(x=>x.id===chosen)||state.rounds[0];$('#currentBall').textContent=r.drawn.at(-1)||'—';$('#drawCount').textContent=`${r.drawn.length}/75`;$('#numberGrid').innerHTML=Array.from({length:75},(_,i)=>`<span class="number ${r.drawn.includes(i+1)?'drawn':''}">${i+1}</span>`).join('');$('#ranking').innerHTML=state.cards.length?state.cards.slice(0,8).map((c,i)=>`<div class="rank-row"><b>#${i+1}</b><span>${c.code}</span><strong>Faltam ${Math.max(0,5-Math.floor(r.drawn.length/15))}</strong></div>`).join(''):'<p class="muted">A classificação aparecerá após a venda e geração das cartelas.</p>'; }
function renderCash(){ const t=totals();$('#cashInitial').textContent=money(state.event.initialCash);$('#cashIncome').textContent=money(t.sales);$('#cashOut').textContent=money(t.prizes+t.withdrawals);$('#cashBalance').textContent=money(t.balance);const rows=[...state.sales.filter(s=>s.status==='valid').map(s=>({at:s.at,type:'Entrada',desc:`Venda ${s.code}`,value:s.value})),...state.withdrawals.map(w=>({at:w.at,type:'Retirada',desc:w.description,value:-w.value}))].sort((a,b)=>b.at.localeCompare(a.at));$('#cashRows').innerHTML=rows.length?rows.map(r=>`<tr><td>${new Date(r.at).toLocaleString('pt-BR')}</td><td>${r.type}</td><td>${r.desc}</td><td>${money(r.value)}</td></tr>`).join(''):'<tr><td colspan="4">Nenhuma movimentação.</td></tr>'; }
function renderReports(){ const t=totals();$('#reportSummary').innerHTML=`<div><span>Vendas confirmadas</span><b>${state.sales.filter(s=>s.status==='valid').length}</b></div><div><span>Cartelas válidas</span><b>${t.cards}</b></div><div><span>Receita</span><b>${money(t.sales)}</b></div><div><span>Premiação</span><b>${money(t.prizes)}</b></div><div><span>Saldo projetado</span><b>${money(t.balance)}</b></div>`;$('#auditRows').innerHTML=state.audit.slice(0,12).map(a=>`<div><b>${a.action}</b><small>${a.user} • ${new Date(a.at).toLocaleString('pt-BR')}</small></div>`).join('')||'<p class="muted">Nenhum registro de auditoria.</p>'; }
function renderSettings(){ $('#cfgName').value=state.event.name;$('#cfgDate').value=state.event.date;$('#cfgPrefix').value=state.settings.prefix;$('#cfgRounds').value=state.event.rounds;$('#cfgCash').value=state.event.initialCash;$('#cfgUnit').value=state.settings.salePrice;$('#cfgTriple').value=state.settings.triplePrice;$('#cfgPrizePercent').value=state.settings.prizePercent;$('#cfgMode').value=state.settings.cardMode; }

function createCard(code,saleId){ const nums=[];while(nums.length<24){const n=Math.ceil(Math.random()*75);if(!nums.includes(n))nums.push(n);}return{id:crypto.randomUUID(),saleId,code,numbers:nums.sort((a,b)=>a-b),status:'valid'}; }
function bind(){
  $('#nav').addEventListener('click',e=>{const b=e.target.closest('button');if(b)navigate(b.dataset.page)});$$('[data-page-target]').forEach(b=>b.onclick=()=>navigate(b.dataset.pageTarget));
  $('#newSale').onclick=()=>$('#saleDialog').showModal();$('#cardQty').oninput=()=>$('#saleTotal').textContent=money(saleValue(Number($('#cardQty').value)));
  $('#saleForm').onsubmit=async e=>{e.preventDefault();const qty=Number($('#cardQty').value),seq=state.sales.length+1,code=`${state.settings.prefix}-${String(seq).padStart(4,'0')}`,id=crypto.randomUUID();const sale={id,code,buyer:$('#buyerName').value.trim(),cpf:$('#buyerCpf').value.trim(),phone:$('#buyerPhone').value.trim(),qty,value:saleValue(qty),at:now(),seller:'Caixa principal',status:'valid'};state.sales.unshift(sale);for(let i=0;i<qty;i++)state.cards.push(createCard(`${code}-${String(i+1).padStart(2,'0')}`,id));audit(`Venda ${code} registrada`);$('#saleDialog').close();e.target.reset();$('#cardQty').value=1;await persist('Venda registrada com sucesso.');};
  $('#saleSearch').oninput=renderSales;$('#saleStatus').onchange=renderSales;
  $('#roundRows').addEventListener('change',async e=>{const el=e.target.closest('[data-round]');if(!el)return;const r=state.rounds.find(x=>x.id===Number(el.dataset.round));r[el.dataset.field]=el.dataset.field==='value'?Number(el.value):el.value;audit(`${r.name} atualizada`);await persist('Rodada atualizada.');});
  $('#suggestPrizes').onclick=async()=>{const pool=totals().sales*Number(state.settings.prizePercent)/100;const first=Math.round((pool*.65)/10)*10,second=Math.round((pool*.35)/10)*10;if(state.rounds[0])state.rounds[0].value=first;if(state.rounds[1])state.rounds[1].value=second;audit('Premiação automática calculada');await persist(`Sugestão aplicada: ${money(first)} e ${money(second)}.`);};
  $('#drawRound').onchange=renderDraw;$('#drawNumber').onclick=async()=>{const r=state.rounds.find(x=>x.id===Number($('#drawRound').value));if(r.drawn.length>=75)return toast('Todos os números já foram sorteados.');let n;do{n=Math.ceil(Math.random()*75)}while(r.drawn.includes(n));r.drawn.push(n);r.status='ready';audit(`Número ${n} sorteado na ${r.name}`);await persist();};$('#undoNumber').onclick=async()=>{const r=state.rounds.find(x=>x.id===Number($('#drawRound').value));const n=r.drawn.pop();if(n){audit(`Sorteio ${n} desfeito`);await persist('Último número removido.');}};
  $('#newWithdrawal').onclick=()=>$('#withdrawDialog').showModal();$('#withdrawForm').onsubmit=async e=>{e.preventDefault();state.withdrawals.unshift({id:crypto.randomUUID(),description:$('#withdrawDesc').value.trim(),value:Number($('#withdrawValue').value),at:now(),user:'Administrador'});audit('Retirada de caixa registrada');$('#withdrawDialog').close();e.target.reset();await persist('Retirada registrada.');};
  $('#saveSettings').onclick=async()=>{const count=Math.max(1,Number($('#cfgRounds').value));state.event.name=$('#cfgName').value.trim();state.event.date=$('#cfgDate').value;state.event.initialCash=Number($('#cfgCash').value);state.event.rounds=count;state.settings.prefix=$('#cfgPrefix').value.trim().toUpperCase();state.settings.salePrice=Number($('#cfgUnit').value);state.settings.triplePrice=Number($('#cfgTriple').value);state.settings.prizePercent=Number($('#cfgPrizePercent').value);state.settings.cardMode=$('#cfgMode').value;while(state.rounds.length<count)state.rounds.push({id:state.rounds.length+1,name:`${state.rounds.length+1}ª Rodada`,prize:'',value:0,status:'waiting',drawn:[]});state.rounds=state.rounds.slice(0,count);audit('Configurações atualizadas');await persist('Configurações salvas.');};
  $('#exportBackup').onclick=async()=>{const r=await window.showApp.exportBackup(state);if(r.ok)toast('Backup exportado com sucesso.');};$('#importBackup').onclick=async()=>{try{const r=await window.showApp.importBackup();if(r.ok){state=r.data;audit('Backup importado');await persist('Backup importado.');}}catch(e){toast(e.message)}};$('#openScreen').onclick=()=>window.showApp.openScreen();
}
(async()=>{state=await window.showApp.load();bind();renderAll();})();
