let state, simpleSave;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}),now=()=>new Date().toISOString();
const methodName=v=>({CASH:'Dinheiro',PIX:'PIX',DEBIT:'Débito',CREDIT:'Crédito'}[v]||'Dinheiro');
const toast=msg=>{const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)};
const audit=action=>state.audit.unshift({at:now(),action,user:'Administrador Master'});
const validSales=()=>state.sales.filter(s=>s.status==='valid');
const saleValue=q=>Math.floor(q/3)*Number(state.settings.triplePrice)+(q%3)*Number(state.settings.salePrice);
function totals(){const sales=validSales().reduce((a,s)=>a+s.value,0),prizes=state.rounds.reduce((a,r)=>a+Number(r.value||0),0),withdrawals=state.withdrawals.reduce((a,w)=>a+w.value,0),cards=validSales().reduce((a,s)=>a+s.qty,0),profit=sales-prizes-withdrawals;return{sales,prizes,withdrawals,cards,profit,balance:Number(state.event.initialCash||0)+profit,margin:sales?profit/sales*100:0,ticket:validSales().length?sales/validSales().length:0}}
async function persist(msg){await window.showApp.save(state);if(msg)toast(msg);renderAll()}
function navigate(id){$$('.page').forEach(p=>p.classList.toggle('active',p.id===id));$$('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===id));$('#pageTitle').textContent=$(`#nav button[data-page="${id}"] span`)?.textContent||'Show de Prêmios'}
function renderAll(){const t=totals(),px=validSales().filter(s=>s.method==='PIX');$('#eventName').textContent=state.event.name;$('#eventDate').textContent=new Date(`${state.event.date}T12:00`).toLocaleDateString('pt-BR',{dateStyle:'long'});$('#eventStatus').textContent=state.event.status==='live'?'EVENTO EM ANDAMENTO':state.event.status==='closed'?'EVENTO ENCERRADO':'EVENTO EM PLANEJAMENTO';$('#mSales').textContent=money(t.sales);$('#mSalesCount').textContent=`${validSales().length} vendas confirmadas`;$('#mCards').textContent=t.cards;$('#mValid').textContent=`${t.cards} válidas`;$('#mPrizes').textContent=money(t.prizes);$('#mBalance').textContent=money(t.balance);$('#mProfit').textContent=money(t.profit);$('#mMargin').textContent=`${t.margin.toFixed(1)}%`;$('#mTicket').textContent=money(t.ticket);$('#mPix').textContent=money(px.reduce((a,s)=>a+s.value,0));$('#mPixCount').textContent=`${px.length} pagamentos`;renderChart();renderActivity();renderNextRound();renderDay();renderSales();renderRounds();renderDraw();renderSellers();renderCash();renderReports();renderUsers();renderPix();renderSettings()}
function renderChart(){const a=[0,0,0,0,0,0,0];validSales().forEach(s=>a[new Date(s.at).getDay()]+=s.value);const max=Math.max(...a,1),d=['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'];$('#salesChart').innerHTML=a.map((v,i)=>`<div class="bar-item"><b>${v?money(v):''}</b><div class="bar" style="height:${Math.max(3,v/max*145)}px"></div><small>${d[i]}</small></div>`).join('')}
function renderActivity(){const e=[...state.sales.map(s=>({at:s.at,op:`Venda ${s.code}`,user:s.seller,value:s.value,status:s.status})),...state.withdrawals.map(w=>({at:w.at,op:w.description,user:w.user,value:-w.value,status:'completed'}))].sort((a,b)=>b.at.localeCompare(a.at)).slice(0,6);$('#activityRows').innerHTML=e.length?e.map(x=>`<tr><td>${new Date(x.at).toLocaleString('pt-BR')}</td><td>${x.op}</td><td>${x.user}</td><td>${money(x.value)}</td><td><span class="pill ${x.status}">${x.status==='valid'?'Confirmada':x.status==='canceled'?'Cancelada':'Concluída'}</span></td></tr>`).join(''):'<tr><td colspan="5">Nenhuma movimentação.</td></tr>'}
function renderNextRound(){const r=state.rounds.find(x=>x.status!=='completed')||state.rounds.at(-1);$('#nextRound').innerHTML=`<div class="round-badge">${r.name}<strong>${r.prize||'Prêmio a definir'}</strong></div><div><small>Premiação</small><h2>${money(r.value)}</h2></div><div class="progress"><span style="width:${Math.min(100,r.drawn.length/75*100)}%"></span></div><small>${r.drawn.length} de 75 números sorteados</small>`}
function renderDay(){const t=totals(),done=state.rounds.filter(r=>r.status==='completed').length;$('#dayStatus').textContent=state.event.status==='live'?'Evento em andamento':state.event.status==='closed'?'Evento encerrado':'Planejamento';$('#toggleEvent').textContent=state.event.status==='live'?'■ Encerrar evento':'▶ Iniciar evento';$('#daySummary').innerHTML=`<div><span>Vendas</span><b>${money(t.sales)}</b></div><div><span>Cartelas</span><b>${t.cards}</b></div><div><span>Rodadas concluídas</span><b>${done}/${state.rounds.length}</b></div><div><span>Saldo projetado</span><b>${money(t.balance)}</b></div>`;$('#dayRoundProgress').textContent=`${done} de ${state.rounds.length} concluídas`;$('#dayRounds').innerHTML=state.rounds.map(r=>`<div class="mini-round ${r.status}"><b>${r.id}</b><span>${r.prize||r.name}</span><small>${money(r.value)}</small></div>`).join('')}
function renderSales(){const q=($('#saleSearch').value||'').toLowerCase(),st=$('#saleStatus').value,m=$('#saleMethod').value;const rows=state.sales.filter(s=>(st==='all'||s.status===st)&&(m==='all'||(s.method||'CASH')===m)&&[s.buyer,s.cpf,s.phone,s.code,s.seller].join(' ').toLowerCase().includes(q));$('#salesRows').innerHTML=rows.length?rows.map(s=>`<tr><td><b>${s.code}</b></td><td>${s.buyer}</td><td>${s.seller||'Caixa principal'}</td><td>${s.qty}</td><td>${methodName(s.method)}</td><td>${money(s.value)}</td><td>${new Date(s.at).toLocaleString('pt-BR')}</td><td><span class="pill ${s.status}">${s.status==='valid'?'Válida':'Cancelada'}</span></td></tr>`).join(''):'<tr><td colspan="8">Nenhuma venda encontrada.</td></tr>'}
function renderRounds(){$('#roundRows').innerHTML=state.rounds.map(r=>`<tr><td><b>${r.id}</b></td><td>${r.name}</td><td><input class="editable" title="Campo editável" data-round="${r.id}" data-field="prize" value="${r.prize||''}" placeholder="✎ Descrição do prêmio"></td><td><input class="editable" title="Campo editável" type="number" data-round="${r.id}" data-field="value" value="${r.value||0}" min="0" step="10"></td><td><span class="pill ${r.status}">${r.status==='ready'?'Pronta':r.status==='completed'?'Concluída':'Aguardando'}</span></td><td>${r.drawn.length}</td></tr>`).join('')}
function renderDraw(){const sel=$('#drawRound'),id=Number(sel.value)||state.rounds.find(r=>r.status!=='completed')?.id||1;sel.innerHTML=state.rounds.map(r=>`<option value="${r.id}" ${r.id===id?'selected':''}>${r.name} — ${r.prize||'sem prêmio'}</option>`).join('');const r=state.rounds.find(x=>x.id===id)||state.rounds[0];$('#currentBall').textContent=r.drawn.at(-1)||'—';$('#drawCount').textContent=`${r.drawn.length}/75`;$('#numberGrid').innerHTML=Array.from({length:75},(_,i)=>`<span class="number ${r.drawn.includes(i+1)?'drawn':''}">${i+1}</span>`).join('');const ranked=state.cards.filter(c=>c.status==='valid').map(c=>({...c,missing:c.numbers.filter(n=>!r.drawn.includes(n)).length})).sort((a,b)=>a.missing-b.missing).slice(0,10);$('#ranking').innerHTML=ranked.length?ranked.map((c,i)=>`<div class="rank-row ${c.missing===0?'winner':''}"><b>#${i+1}</b><span>${c.code}</span><strong>${c.missing===0?'VENCEDORA':`Faltam ${c.missing}`}</strong></div>`).join(''):'<p class="muted">A classificação aparecerá após a venda das cartelas.</p>'}
function renderSellers(){const stats=state.sellers.map(s=>{const sales=validSales().filter(v=>v.sellerId===s.id||v.seller===s.name),revenue=sales.reduce((a,v)=>a+v.value,0);return{...s,count:sales.length,cards:sales.reduce((a,v)=>a+v.qty,0),revenue,earned:revenue*Number(s.commission||0)/100}}).sort((a,b)=>b.revenue-a.revenue);$('#sellerActive').textContent=state.sellers.filter(s=>s.active).length;$('#sellerTop').textContent=stats[0]?.name||'—';$('#sellerRevenue').textContent=money(stats.reduce((a,s)=>a+s.revenue,0));$('#sellerCommission').textContent=money(stats.reduce((a,s)=>a+s.earned,0));$('#sellerRows').innerHTML=stats.map(s=>`<tr><td><b>${s.name}</b></td><td>${s.phone||'—'}</td><td>${s.count}</td><td>${s.cards}</td><td>${money(s.revenue)}</td><td>${money(s.earned)} (${s.commission||0}%)</td><td><span class="pill ${s.active?'valid':'canceled'}">${s.active?'Ativo':'Inativo'}</span></td></tr>`).join('');$('#saleSeller').innerHTML=state.sellers.filter(s=>s.active).map(s=>`<option value="${s.id}">${s.name}</option>`).join('')}
function renderCash(){const t=totals();$('#cashInitial').textContent=money(state.event.initialCash);$('#cashIncome').textContent=money(t.sales);$('#cashOut').textContent=money(t.prizes+t.withdrawals);$('#cashBalance').textContent=money(t.balance);$('#paymentStrip').innerHTML=['CASH','PIX','DEBIT','CREDIT'].map(m=>`<div><span>${methodName(m)}</span><b>${money(validSales().filter(s=>(s.method||'CASH')===m).reduce((a,s)=>a+s.value,0))}</b></div>`).join('');const rows=[...validSales().map(s=>({at:s.at,type:'Entrada',desc:`Venda ${s.code}`,method:methodName(s.method),value:s.value})),...state.withdrawals.map(w=>({at:w.at,type:'Retirada',desc:w.description,method:'Caixa',value:-w.value}))].sort((a,b)=>b.at.localeCompare(a.at));$('#cashRows').innerHTML=rows.length?rows.map(r=>`<tr><td>${new Date(r.at).toLocaleString('pt-BR')}</td><td>${r.type}</td><td>${r.desc}</td><td>${r.method}</td><td>${money(r.value)}</td></tr>`).join(''):'<tr><td colspan="5">Nenhuma movimentação.</td></tr>'}
function renderReports(){const t=totals();$('#reportSummary').innerHTML=`<div><span>Vendas confirmadas</span><b>${validSales().length}</b></div><div><span>Cartelas válidas</span><b>${t.cards}</b></div><div><span>Receita</span><b>${money(t.sales)}</b></div><div><span>Premiação</span><b>${money(t.prizes)}</b></div><div><span>Lucro líquido</span><b>${money(t.profit)}</b></div><div><span>Margem</span><b>${t.margin.toFixed(1)}%</b></div><div><span>Saldo projetado</span><b>${money(t.balance)}</b></div>`;$('#auditRows').innerHTML=state.audit.slice(0,18).map(a=>`<div><b>${a.action}</b><small>${a.user} • ${new Date(a.at).toLocaleString('pt-BR')}</small></div>`).join('')||'<p class="muted">Nenhum registro.</p>'}
function renderUsers(){const roles={MASTER:'Acesso total',ADMIN:'Gerenciamento',OPERATOR:'Vendas e operação',VIEWER:'Somente consulta'};$('#userRows').innerHTML=state.users.map(u=>`<tr><td><b>${u.name}</b></td><td>${u.login}</td><td>${u.role}</td><td>${roles[u.role]||'Personalizado'}</td><td><span class="pill ${u.active?'valid':'canceled'}">${u.active?'Ativo':'Inativo'}</span></td></tr>`).join('')}
function renderPix(){const p=state.settings.pix;$('#pixEnabled').checked=!!p.enabled;$('#pixType').value=p.keyType;$('#pixKey').value=p.key;$('#pixName').value=p.name;$('#pixCity').value=p.city;$('#pixDescription').value=p.description;$('#pixBanner').value=p.banner;$('#pixPreviewBanner').textContent=p.banner||'PAGUE COM PIX DIRETO DO SEU LUGAR'}
function renderSettings(){$('#cfgName').value=state.event.name;$('#cfgDate').value=state.event.date;$('#cfgPrefix').value=state.settings.prefix;$('#cfgRounds').value=state.event.rounds;$('#cfgCash').value=state.event.initialCash;$('#cfgUnit').value=state.settings.salePrice;$('#cfgTriple').value=state.settings.triplePrice;$('#cfgPrizePercent').value=state.settings.prizePercent;$('#cfgFirstShare').value=state.settings.firstPrizeShare;$('#cfgSecondShare').value=state.settings.secondPrizeShare;$('#cfgMode').value=state.settings.cardMode}
function createCard(code,saleId){const nums=[];while(nums.length<24){const n=Math.ceil(Math.random()*75);if(!nums.includes(n))nums.push(n)}return{id:crypto.randomUUID(),saleId,code,numbers:nums.sort((a,b)=>a-b),status:'valid'}}
function simpleDialog(title,fields,save){$('#simpleTitle').textContent=title;$('#simpleFields').innerHTML=fields.map(f=>`<label>${f.label}${f.type==='select'?`<select id="sf_${f.id}">${f.options.map(o=>`<option value="${o.value}">${o.label}</option>`).join('')}</select>`:`<input id="sf_${f.id}" type="${f.type||'text'}" ${f.required?'required':''} value="${f.value||''}">`}</label>`).join('');simpleSave=save;$('#simpleDialog').showModal()}
function bind(){
  $('#nav').onclick=e=>{const b=e.target.closest('button');if(b)navigate(b.dataset.page)};$$('[data-page-target]').forEach(b=>b.onclick=()=>navigate(b.dataset.pageTarget));setInterval(()=>$('#dayClock').textContent=new Date().toLocaleTimeString('pt-BR'),1000);$('#openScreen').onclick=$('#dayScreen').onclick=()=>window.showApp.openScreen();$('#toggleEvent').onclick=async()=>{state.event.status=state.event.status==='live'?'closed':'live';audit(state.event.status==='live'?'Evento iniciado':'Evento encerrado');await persist('Status atualizado.')};
  $('#newSale').onclick=()=>{$('#saleDialog').showModal();renderSellers()};$('#cardQty').oninput=()=>$('#saleTotal').textContent=money(saleValue(Number($('#cardQty').value)));$('#saleForm').onsubmit=async e=>{e.preventDefault();const qty=Number($('#cardQty').value),seq=state.sales.length+1,code=`${state.settings.prefix}-${String(seq).padStart(4,'0')}`,id=crypto.randomUUID(),seller=state.sellers.find(s=>s.id===Number($('#saleSeller').value))||state.sellers[0],sale={id,code,buyer:$('#buyerName').value.trim(),cpf:$('#buyerCpf').value.trim(),phone:$('#buyerPhone').value.trim(),qty,value:saleValue(qty),at:now(),seller:seller.name,sellerId:seller.id,method:$('#paymentMethod').value,status:'valid',priceSnapshot:{unit:state.settings.salePrice,triple:state.settings.triplePrice}};state.sales.unshift(sale);state.customers.push({id:crypto.randomUUID(),name:sale.buyer,cpf:sale.cpf,phone:sale.phone,createdAt:sale.at});for(let i=0;i<qty;i++)state.cards.push(createCard(`${code}-${String(i+1).padStart(2,'0')}`,id));audit(`Venda ${code} registrada em ${methodName(sale.method)}`);$('#saleDialog').close();e.target.reset();$('#cardQty').value=1;await persist('Venda registrada.')};$('#saleSearch').oninput=renderSales;$('#saleStatus').onchange=$('#saleMethod').onchange=renderSales;
  $('#roundRows').onchange=async e=>{const el=e.target.closest('[data-round]');if(!el)return;const r=state.rounds.find(x=>x.id===Number(el.dataset.round));r[el.dataset.field]=el.dataset.field==='value'?Number(el.value):el.value;audit(`${r.name} atualizada`);await persist('Rodada atualizada.')};$('#suggestPrizes').onclick=async()=>{const pool=totals().sales*state.settings.prizePercent/100,first=Math.round(pool*state.settings.firstPrizeShare/100/10)*10,second=Math.round(pool*state.settings.secondPrizeShare/100/10)*10;if(state.rounds[0])state.rounds[0].value=first;if(state.rounds[1])state.rounds[1].value=second;audit('Premiação sugerida');await persist(`Sugestão: ${money(first)} e ${money(second)}.`)};
  $('#drawRound').onchange=renderDraw;$('#drawNumber').onclick=async()=>{const r=state.rounds.find(x=>x.id===Number($('#drawRound').value));if(r.drawn.length>=75)return toast('Todos os números já foram sorteados.');let n;do n=Math.ceil(Math.random()*75);while(r.drawn.includes(n));r.drawn.push(n);r.status='ready';audit(`Número ${n} sorteado`);await persist()};$('#undoNumber').onclick=async()=>{const r=state.rounds.find(x=>x.id===Number($('#drawRound').value)),n=r.drawn.pop();if(n){audit(`Sorteio ${n} desfeito`);await persist('Último número removido.')}};
  $('#newSeller').onclick=()=>simpleDialog('Novo vendedor',[{id:'name',label:'Nome',required:true},{id:'phone',label:'Telefone'},{id:'commission',label:'Comissão (%)',type:'number',value:0}],async()=>{state.sellers.push({id:Date.now(),name:$('#sf_name').value.trim(),phone:$('#sf_phone').value.trim(),commission:Number($('#sf_commission').value),active:true});audit('Vendedor cadastrado');await persist('Vendedor cadastrado.')});$('#newUser').onclick=()=>simpleDialog('Novo usuário',[{id:'name',label:'Nome',required:true},{id:'login',label:'Login',required:true},{id:'role',label:'Perfil',type:'select',options:[{value:'ADMIN',label:'Administrador'},{value:'OPERATOR',label:'Operador'},{value:'VIEWER',label:'Consulta'}]}],async()=>{state.users.push({id:Date.now(),name:$('#sf_name').value.trim(),login:$('#sf_login').value.trim(),role:$('#sf_role').value,active:true});audit('Usuário cadastrado');await persist('Usuário cadastrado.')});$('#simpleForm').onsubmit=async e=>{e.preventDefault();$('#simpleDialog').close();if(simpleSave)await simpleSave()};
  $('#newWithdrawal').onclick=()=>$('#withdrawDialog').showModal();$('#withdrawForm').onsubmit=async e=>{e.preventDefault();state.withdrawals.unshift({id:crypto.randomUUID(),description:$('#withdrawDesc').value.trim(),value:Number($('#withdrawValue').value),at:now(),user:'Administrador Master'});audit('Retirada registrada');$('#withdrawDialog').close();e.target.reset();await persist('Retirada registrada.')};$('#closeCash').onclick=()=>simpleDialog('Fechamento de caixa',[{id:'counted',label:'Valor contado (R$)',type:'number',required:true,value:totals().balance}],async()=>{const expected=totals().balance,counted=Number($('#sf_counted').value);state.cashClosings.unshift({id:crypto.randomUUID(),at:now(),expected,counted,difference:counted-expected,user:'Administrador Master'});audit(`Caixa fechado; diferença ${money(counted-expected)}`);await persist(`Diferença: ${money(counted-expected)}.`)});
  $('#savePix').onclick=async()=>{state.settings.pix={enabled:$('#pixEnabled').checked,keyType:$('#pixType').value,key:$('#pixKey').value.trim(),name:$('#pixName').value.trim(),city:$('#pixCity').value.trim(),description:$('#pixDescription').value.trim(),banner:$('#pixBanner').value.trim()};audit('PIX atualizado');await persist('Configuração PIX salva.')};$('#testPix').onclick=async()=>{try{const p={keyType:$('#pixType').value,key:$('#pixKey').value.trim(),name:$('#pixName').value.trim(),city:$('#pixCity').value.trim(),description:$('#pixDescription').value.trim()},r=await window.showApp.pixQr(p,Number($('#pixTestValue').value),'TESTE');$('#pixQr').src=r.dataUrl;$('#pixQr').style.display='block';$('#pixQrEmpty').style.display='none';$('#pixPayload').textContent=r.payload;toast('QR PIX gerado.')}catch(e){toast(e.message)}};
  $('#saveSettings').onclick=async()=>{const count=Math.max(1,Number($('#cfgRounds').value));Object.assign(state.event,{name:$('#cfgName').value.trim(),date:$('#cfgDate').value,initialCash:Number($('#cfgCash').value),rounds:count});Object.assign(state.settings,{prefix:$('#cfgPrefix').value.trim().toUpperCase(),salePrice:Number($('#cfgUnit').value),triplePrice:Number($('#cfgTriple').value),prizePercent:Number($('#cfgPrizePercent').value),firstPrizeShare:Number($('#cfgFirstShare').value),secondPrizeShare:Number($('#cfgSecondShare').value),cardMode:$('#cfgMode').value});while(state.rounds.length<count)state.rounds.push({id:state.rounds.length+1,name:`${state.rounds.length+1}ª Rodada`,prize:'',value:0,status:'waiting',drawn:[]});state.rounds=state.rounds.slice(0,count);audit('Configurações atualizadas');await persist('Configurações salvas.')};
  $('#printReport').onclick=()=>window.print();$('#exportBackup').onclick=async()=>{const r=await window.showApp.exportBackup(state);if(r.ok)toast('Backup exportado.')};$('#importBackup').onclick=async()=>{try{const r=await window.showApp.importBackup();if(r.ok){state=r.data;audit('Backup importado');await persist('Backup importado.')}}catch(e){toast(e.message)}}
}
(async()=>{state=await window.showApp.load();bind();renderAll()})();
